### ISSUE TITLE
Add an option to remove the whitespace after/before the braces

### ISSUE THREAD

**Issue by kewah** [wbinnssmith/esformatter-collapse-objects#1]
Hi,

Currently it collapses the object expression by adding a whitespace before/after the curly braces.
```js
var foo = { foo: 1, bar: 2 };
```
See https://github.com/wbinnssmith/esformatter-collapse-objects/blob/master/index.js#L123-L126

It would be nice to add an option to remove the whitespace after/before the curly braces.
```js
var foo = {foo: 1, bar: 2};
```

Thanks

**Comment by jzaefferer** [comment]
That should use existing esformatter configuration if possible, like `whiteSpace.after.ObjectExpressionOpeningBrace` and `whiteSpace.before.ObjectExpressionClosingBrace`.

**Comment by kewah** [comment]
@jzaefferer `whiteSpace.after.ObjectExpressionOpeningBrace` and `whiteSpace.before.ObjectExpressionClosingBrace` are not implemented yet, right ? It's only available for `lineBreak`

**Comment by jzaefferer** [comment]
Just because its not in the `default.json` doesn't mean it doesn't exist, would've to check the actual hooks for that. But since plugins usually run after esformatter, it needs to be reimplemented in here anyway.

**Comment by kewah** [comment]
@jzaefferer thx for your feedback

**Comment by wbinnssmith** [comment]
So I spent some time looking into implementing this. The thing with reusing
the existing config values is that the expressions would have both new
lines *and* spaces before/after the braces, which doesn't make much sense
at all, because one or the other is triggered conditionally. What do you
guys think?

**Comment by kewah** [comment]
What if we do something like that? Checking the previous/next token to detect if we should add or not a whitespace.

```js
if (_tk.isBr(token)) {
  // Remove all whitespace/indent after the line break
  var next = token.next;
  while (_tk.isEmpty(next)) {
    _tk.remove(next);
    next = next.next;
  }

  var value = token.prev.value === '{' || token.prev.value === '}' || token.next.value === '}'
    ? '' // Read the value from the options
    : ' ';

  _tk.before(token, {
    type: 'WhiteSpace',
    value: value
  });

  // Remove the line break itself
  _tk.remove(token);
}
```

Don't know if there is a cleaner way of doing it.

**Comment by millermedeiros** [comment]
important to note that `rocambole-whitespace` (used internally by esformatter) doesn't add a white space at the beginning or end of the line. So the line break rule actually changes the meaning of `whiteSpace.before.ObjectExpressionClosingBrace = 1` (it only adds the white space if `}` is not the first token of the line).

the PR #2 takes care of the edge cases and should work as expected.
