### ISSUE TITLE
Option to just leave objects alone?

### ISSUE THREAD

**Issue by bclinkinbeard** [wbinnssmith/esformatter-collapse-objects#6]
Can I make the formatter just never reformat an object? I don't have any hard and fast rules for when I want an object to be single or multi line, so I'd like the formatter to just ignore them.

Possible?

**Comment by wbinnssmith** [comment]
Yeah it's definitely possible and I see the use, for sure. I'll see when I can get around to it. Open to PRs though!

**Comment by wbinnssmith** [comment]
I just added this functionality with v0.5 through 7013214. Just set "ObjectExpression" to `-1`.

**Comment by bclinkinbeard** [comment]
Awesome, thanks!
